language: java
deploy:
  provider: heroku
  api_key:
    secure: Ltn+xnxMWKjitBQnc8FV72FaPXypqv7CB8we4epw67HFknAnYWcVJwrhhZIp4+49HSurw8yHyvNHpGMNBiRj2n660PMuAeJvTnqk5jWVjEaJA3IVvG8X23Fn0KBLQ7vqRVhz1UuLH9Yik6tBl8XZRAGkEsyaRYcqr+TC3ISzpJjVlruUHIxCxDThDJ0VpN22zAaBYf4ptd6PdrESLXrHiUr2E1fg7qtSY+Ke/b9yhWsSPMFGxY7zYS0+qiHSTOSNwibTK6HEcWzy1cJMf4CMuz61hvshLfT1o6ITQrPgDF3O0xeSXgkTMNA9hPZuRpPOIeMPfG2HjoIr+uoWJnWw3RK8z3GVs7EMBQw1X65uJTM8l1lwiy8nwTHeY5yVsDHBWwz4epZFaZL1tUksQln698jjhSQYSfSL8EvzB2cGrszi52NAYVTKMPLCXHP8QCAxO7X3fGDl1cyZxEBIa5YHml8YY0ROjK5Ee1NpZA1RjBlkxw0gXJp1SUWyaScYKE5wlw6Rq9sir8C9ugRmN6NBf8cDDY06R3iKJSfSZrCyhT5c7QDnF1t3DrasHFUghyRCZDkDw0XCVmfi1pk6x4ok5fTmN+IGhm8eIB+RRbcGxKXsbIVuwCPwTChRwIAPu8VNcFn+XoRta4U1gmdyorBNpJlhH35yR6Iqao5ph656C/w=
  app: still-cliffs-71498
