language: java
deploy:
  provider: heroku
  api_key:
    secure: K0W5VoukVqL4dfTfiqCDvjg6GfLX39nCo0NvHpX3fsAxDAIIN6sTkPopAgWRkfLWTnqtzTX2ivb6SCmjsQni0KP6NTaYMggFPHhNPwSIGko6o7S7oUba7PO79qVSY0OWxjlHgli3aboPINj8OrqEl3byegSdy42U0gJIpC/k/dNEhLsEe8FjprdWZxBmb/UuiYfYUKYd0m4IMJ/Liy3Ebd5ustPjH5fSup4XDK9PWLR/e+hE+hdb8v63MIj3E1trPwaBows+2fUrqyVhXQEsc7w/UPmLr/qdYHGIuJ8U233l2fGz8RD6//98Xg956WhYF1x6kRFyHqJxVrx6kl3ioeoYsZPrc3BA8Gn5VrSrqjx4hNUSiZHq4aoB4A/UVHTT6sU1GQPje1auo5j13vO3NfRPVdXzci90TSH+wY4U5fWwrOOkrlV2uK5gIHrb5raFvQyNw4f5MZBs7WYB5n2X0AQ3y50Pumf5vQhcYDdL1v4Xr1vUBBKuX7NbQ6eIpTFbrxH+AQ77gGGF6k1a/nwqZkWHsC5g5yI9EjMgyX6oK5hwhvv7e3OowOmfoWp8EJpB/SfzJ45yk1MzzkayBp4bxxiMAskLOZyUE0QJWZTuqKivZ38rsMMJX3hm/wxc9RPttkBM/3vSgc415irTTu1pCFCjkdZyZBZevmX14umSqME=
  app: still-cliffs-71498
